/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  org.jetbrains.annotations.NotNull
 */
package com.boehmod.blockfront.common.world;

import com.boehmod.blockfront.common.world.ExplosionAudioConfig;
import com.boehmod.blockfront.registry.BFSounds;
import org.jetbrains.annotations.NotNull;

public class ExplosionAudioConfigs {
    @NotNull
    public static final ExplosionAudioConfig GENERIC = new ExplosionAudioConfig().ambience(BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE, BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE_DISTANT, BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE_INDOORS, BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE_INDOORS_DISTANT).nose(BFSounds.AMBIENT_EXPLOSION_GRENADE_NOSE, BFSounds.AMBIENT_EXPLOSION_GRENADE_NOSE_DISTANT).explode(BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE_INDOORS, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE_STEREO, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_DISTANT, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_DISTANT_INDOORS).bass(BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_BASS);
    @NotNull
    public static final ExplosionAudioConfig ARTILLERY = new ExplosionAudioConfig().ambience(BFSounds.AMBIENT_EXPLOSION_ARTILLERY_AMBIENCE, BFSounds.AMBIENT_EXPLOSION_ARTILLERY_AMBIENCE_DISTANT, BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE_INDOORS, BFSounds.AMBIENT_EXPLOSION_GRENADE_AMBIENCE_INDOORS_DISTANT).nose(BFSounds.AMBIENT_EXPLOSION_GRENADE_NOSE, BFSounds.AMBIENT_EXPLOSION_GRENADE_NOSE_DISTANT).explode(BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE_INDOORS, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_CLOSE_STEREO, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_DISTANT, BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_DISTANT_INDOORS).bass(BFSounds.AMBIENT_EXPLOSION_GRENADE_EXPLODE_BASS);
}

