modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0"

[[mixins]]
config = "mercfrontcore.mixins.json"

[[mods]]
modId = "mercfrontcore"
version = "1.0.8-0.7.1.2b"
displayName = "FrontCore"
authors = "TomerDev (credit to OG author of front-utilities: forteus19)"
description = '''Helper stuff for BlockFront with proxy compatibility. Credit to the OG author: forteus19 (https://github.com/forteus19/Front-Utilities).'''
logoFile = "logo.png"

[[dependencies.mercfrontcore]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.215,22.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mercfrontcore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mercfrontcore]]
modId = "bf"
type = "required"
versionRange = "[0.7.1.2b]"
ordering = "AFTER"
side = "BOTH"
